version: "3"

services:
  php:
    build: ./.docker/php
    volumes:
      - .:/app
      - ./.runtime/cache/composer:/.composer/cache
    working_dir: /app
    user: $USER_ID:$GROUP_ID
    depends_on:
      - redis
    ports:
      - 1999:1999

  # queue:
  #   build: ./.docker/php
  #   volumes:
  #     - .:/app
  #   working_dir: /app

  nginx:
    image: nginx:alpine
    volumes:
      - .:/app:ro
    working_dir: /app
    depends_on:
      - php
    networks:
      default:
        aliases:
          - api.nginx

  redis:
    image: redis:7.0.9-alpine3.17
    volumes:
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
