services:
  php:
    build: ./.docker/php
    volumes:
      - .:/app
      - ./.runtime/cache/composer:/.composer/cache
    working_dir: /app
    user: $USER_ID:$GROUP_ID
    depends_on:
      - redis

  queue:
    build: ./.docker/php
    volumes:
      - .:/app
    working_dir: /app

  ratchet:
    build: ./.docker/php
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "php artisan ws:listen"

  soketi:
    image: quay.io/soketi/soketi:0.34-16-distroless
    command: /app/bin/server.js start --config=/config.json
    volumes:
      - ./.docker/soketi/config.json:/config.json:ro

  nginx:
    image: nginx:alpine
    volumes:
      - .:/app:ro
    working_dir: /app
    depends_on:
      - php
      - soketi
    networks:
      default:
        aliases:
          - api.nginx

  redis:
    image: redis:7-alpine3.19
    volumes:
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
